---

# @action Ensures cloudflared is installed
# Installs cloudflared on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: 'install-{{ ansible_system }}.yml'

- name: Configure cloudflared
  become: true
  block:
    - include_tasks: 'configure-cloudflared.yml'
