- name: Install base collection of Brew packages
  become: true
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    # Other useful libraries
    - git # Should already be installed but want to be safe
    - jq # json query
    - yq # yaml query
    - curl # openssl based curl
    - gnu-sed
    - gnu-tar
    - nano
  when: ansible_os_family == 'Darwin'

- name: Install base collection of apps via Brew Cask
  become: true
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
    accept_external_apps: true
  with_items:
    - docker
    - visual-studio-code
  when: ansible_os_family == 'Darwin'

- name: Install/update Debian base packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - git
      - jq
      - sqlite3
      - curl
      - unzip
      - wget
      - tree
      - nano
    state: latest
  when: ansible_os_family == 'Debian'

- name: Update repositories and install/update Alpine base packages
  become: true
  community.general.apk:
    name: 
      - git
      - jq
      - sqlite3
      - curl
      - unzip
      - wget
      - tree
      - nano
    state: latest
    update_cache: true
    upgrade: true
  when: ansible_os_family == 'Alpine'

- name: Update repositories and install/update Archlinux base packages
  become: true
  community.general.pacman:
    name: 
      - git
      - jq
      - sqlite3
      - curl
      - unzip
      - wget
      - tree
      - nano
    state: latest
    update_cache: true
  when: ansible_os_family == 'Archlinux'
